import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[auto_1fr_auto] h-svh`}
      >
      <header>
            <div className="container mx-auto px-4 py-3">
                <h1 className="text-2xl font-bold">OpeniddictPlus UI</h1>
            </div>
      </header>
      <main>
          <div className="container mx-auto px-4 py-3">
              {children}
          </div>
      </main>
      <footer className="border-t-2 py-3">
          <div className="container mx-auto px-4">
              &copy; 2025 - AspNetCore OpeniddictPlus UI
          </div>
      </footer>
      </body>
    </html>
  );
}
